import type { ProductFormValues } from "./product-form.types";

export const defaultProductFormValues: ProductFormValues = {
  productNameEn: "",
  productNameAr: "",
  productCode: "",
  brandId: "",
  categoryId: "",
  groupId: "",
  shortDescriptionEn: "",
  shortDescriptionAr: "",
  fullDescriptionEn: "",
  fullDescriptionAr: "",
  usageInstructionsEn: "",
  usageInstructionsAr: "",
  seoTitleEn: "",
  seoTitleAr: "",
  seoDescriptionEn: "",
  seoDescriptionAr: "",
  stockStatus: "in_stock",
  isBestSeller: false,
  displayOrder: 0,
  highlights: [
    { id: "h1", textEn: "", textAr: "" },
    { id: "h2", textEn: "", textAr: "" },
    { id: "h3", textEn: "", textAr: "" },
  ],
  featureIcons: [],
  colors: [],
  selectedColorId: null,
  optionGroups: [],
  galleryImages: [],
  video: null,
};
