import type { PublicLang } from "./shared";

export const homePageCopy = {
  en: {
    heroBadge: "CHOUHA STATIONERY & OFFICE SUPPLIES",
    heroTitle: "Real products, cleaner browsing, and a front page that feels ready for business.",
    heroBody:
      "Browse published products, move through brands directly from the homepage, and reach the right inquiry path without guessing.",
    exploreProducts: "Explore Products",
    contactUs: "Contact Us",
    totalProducts: "Published products",
    totalBrands: "Brands",
    totalCategories: "Categories",
    familiesBadge: "PRODUCT FAMILIES",
    familiesTitle: "Browse product families from real catalog data",
    familiesAction: "Open catalog",
    productsTitle: "Featured products",
    productsAction: "View all products",
    viewProduct: "View Product",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    fallbackDescription: "Product description will appear here.",
    brandTitle: "Brands we present",
    brandAction: "See all brands",
    brandFallbackPrefix: "Brand:",
    contactBadge: "CONTACT & INQUIRY",
    contactTitle: "Need a product, a brand, or a wholesale conversation?",
    contactBody:
      "Direct visitors toward product discovery, brand-based browsing, and quick support without forcing them through a long path.",
    contactAction: "Get In Touch",
    supportBadge: "WE'RE HERE TO HELP",
    supportTitle: "Support & quick access",
    supportAction: "Open",
    inquiryTitle: "Product Inquiry",
    inquiryText: "Jump into the product list and pick the item you want to ask about.",
    brandSupportTitle: "Brand Support",
    brandSupportText: "Browse by brand and head straight into the filtered catalog.",
    contactCardTitle: "Contact Us",
    contactCardText: "Open the contact page for location details and direct communication.",
    corporateTitle: "Corporate Orders",
    corporateText: "Use the contact route for bulk and business supply requests.",
    productCountSuffix: "products",
    loadErrorFallback: "Unable to load homepage data right now.",
    noProducts: "Published products will appear here after they are added from the admin panel.",
    noBrands: "Brands will appear here once they are added to the catalog.",
  },
  ar: {
    heroBadge: "شوحة للقرطاسية واللوازم المكتبية",
    heroTitle: "منتجات حقيقية، تصفح أوضح، وصفحة رئيسية جاهزة للشغل.",
    heroBody:
      "تصفح المنتجات المنشورة، انتقل بين البراندات مباشرة من الصفحة الرئيسية، ووصل الزائر للمسار الصحيح بدون تعقيد.",
    exploreProducts: "استعرض المنتجات",
    contactUs: "تواصل معنا",
    totalProducts: "منتجات منشورة",
    totalBrands: "براندات",
    totalCategories: "فئات",
    familiesBadge: "عائلات المنتجات",
    familiesTitle: "تصفح عائلات المنتجات من بيانات الكتالوج الحقيقية",
    familiesAction: "فتح الكتالوج",
    productsTitle: "منتجات مميزة",
    productsAction: "كل المنتجات",
    viewProduct: "عرض المنتج",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    fallbackDescription: "سيظهر وصف المنتج هنا.",
    brandTitle: "البراندات التي نعرضها",
    brandAction: "عرض كل البراندات",
    brandFallbackPrefix: "براند:",
    contactBadge: "التواصل والاستفسارات",
    contactTitle: "تبحث عن منتج أو براند أو طلب جملة؟",
    contactBody:
      "وجّه الزائر إلى استكشاف المنتجات أو التصفح حسب البراند أو الوصول السريع للدعم بدون لف طويل.",
    contactAction: "تواصل الآن",
    supportBadge: "نحن هنا للمساعدة",
    supportTitle: "الدعم والوصول السريع",
    supportAction: "فتح",
    inquiryTitle: "استفسار عن منتج",
    inquiryText: "ادخل إلى قائمة المنتجات واختر المنتج الذي تريد السؤال عنه.",
    brandSupportTitle: "دعم البراندات",
    brandSupportText: "تصفح حسب البراند وادخل مباشرة إلى الكتالوج المفلتر.",
    contactCardTitle: "تواصل معنا",
    contactCardText: "افتح صفحة التواصل لمعلومات الموقع ووسائل التواصل المباشر.",
    corporateTitle: "طلبات الشركات",
    corporateText: "استخدم مسار التواصل لطلبات الجملة والتوريد التجاري.",
    productCountSuffix: "منتج",
    loadErrorFallback: "تعذر تحميل بيانات الصفحة الرئيسية حالياً.",
    noProducts: "ستظهر المنتجات المنشورة هنا بعد إضافتها من لوحة الأدمن.",
    noBrands: "ستظهر البراندات هنا بعد إضافتها إلى الكتالوج.",
  },
} as const satisfies Record<PublicLang, Record<string, string>>;
